// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{}, true)
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	usersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(usersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Users, error)
		FindOneByEmail(ctx context.Context, email string) (*Users, error)
		FindOneByGoogleId(ctx context.Context, googleId sql.NullString) (*Users, error)
		FindOneByPhoneNumber(ctx context.Context, phoneNumber string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Users struct {
		Id              int64          `db:"id"`
		Email           string         `db:"email"`
		PhoneNumber     string         `db:"phone_number"`
		PasswordHash    sql.NullString `db:"password_hash"`
		GoogleId        sql.NullString `db:"google_id"`
		IsActive        bool           `db:"is_active"`
		EmailVerifiedAt sql.NullTime   `db:"email_verified_at"`
		PhoneVerifiedAt sql.NullTime   `db:"phone_verified_at"`
		LastLoginAt     sql.NullTime   `db:"last_login_at"`
		CreatedAt       time.Time      `db:"created_at"`
		UpdatedAt       time.Time      `db:"updated_at"`
	}
)

func newUsersModel(conn sqlx.SqlConn) *defaultUsersModel {
	return &defaultUsersModel{
		conn:  conn,
		table: `"crm_schema"."users"`,
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id int64) (*Users, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", usersRows, m.table)
	var resp Users
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByEmail(ctx context.Context, email string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where email = $1 limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByGoogleId(ctx context.Context, googleId sql.NullString) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where google_id = $1 limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, googleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByPhoneNumber(ctx context.Context, phoneNumber string) (*Users, error) {
	var resp Users
	query := fmt.Sprintf("select %s from %s where phone_number = $1 limit 1", usersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, phoneNumber)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, usersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Email, data.PhoneNumber, data.PasswordHash, data.GoogleId, data.IsActive, data.EmailVerifiedAt, data.PhoneVerifiedAt, data.LastLoginAt)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, usersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Email, newData.PhoneNumber, newData.PasswordHash, newData.GoogleId, newData.IsActive, newData.EmailVerifiedAt, newData.PhoneVerifiedAt, newData.LastLoginAt)
	return err
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
