CREATE TABLE crm_schema.admin_refresh_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    family_id UUID NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NULL,
    replaced_by_session_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_refresh_sessions_user
        FOREIGN KEY (user_id) REFERENCES crm_schema.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_refresh_sessions_replacement
        FOREIGN KEY (replaced_by_session_id)
        REFERENCES crm_schema.admin_refresh_sessions(id) ON DELETE SET NULL,
    CONSTRAINT chk_admin_refresh_sessions_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT chk_admin_refresh_sessions_not_self_replaced
        CHECK (replaced_by_session_id IS NULL OR replaced_by_session_id <> id)
);

CREATE UNIQUE INDEX uq_admin_refresh_sessions_active_family
    ON crm_schema.admin_refresh_sessions (family_id)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_admin_refresh_sessions_user_id
    ON crm_schema.admin_refresh_sessions (user_id);

CREATE INDEX idx_admin_refresh_sessions_expiry
    ON crm_schema.admin_refresh_sessions (expires_at);
