// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"webtranshome/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Cek status server dan koneksi database
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
